### ISSUE TITLE
Get extension to work in Firefox

### ISSUE THREAD

**Issue by jtl3d** [ditinc/bugzilla-github-extension#31]
Firefox's WebExtension API should mean the plugin will just work in FF.  I tried it, and it does partially work, but any call to Bugzilla is tripping a cross domain policy error.  I don't know why, I've tried adding the appropriate permissions, but in Chrome the content-scripts run in their own CSP so you can do XSS just fine... maybe a future update will work, or maybe we should move the calls from the content-script to the background page?  Either way, it's so close to working in FF!

**Comment by jgmize** [comment]
Now that [bug 1232849](https://bugzilla.mozilla.org/show_bug.cgi?id=1232849) has been fixed, it is now possible to [modify the CSP](https://github.com/codesy/widgets/blob/master/src/csp.js) using [webrequest.onHeadersRecieved](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onHeadersReceived).

**Comment by jtl3d** [comment]
Adding the https://*/* to the permissions fixed it for me, and I was able to deploy in FF. Some things aren't working, but I can close this.
